name: flutter_barcode_scanner
description: A Flutter barcode scanner.
version: 0.0.1
author: Jort de Bokx
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.github.jortdebokx.flutter_barcode_scanner
        pluginClass: FlutterBarcodeScannerPlugin
      ios:
        pluginClass: FlutterBarcodeScannerPlugin
